gcp:
  project_id: "project-f0ff9de1-dfa0-4dca-957"
  region: "us-central1"

bigquery:
  dataset_id: "world_weather_dataset"
  table_id: "world_air_quality"
  columns: "city, temp, humidity, wind_speed, pm25_value"
  row_limit: 100

vector_store:
  collection_name: "air_quality_records"
  storage_path: "src/data/local_qdrant_storage"
  embedding_model: "gemini-embedding-001"
